/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o e:\nim\stream\2015_11_29\nimcache\streams.o e:\nim\stream\2015_11_29\nimcache\streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
typedef struct Ioerror4031 Ioerror4031;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell49346 Cell49346;
typedef struct Cellseq49362 Cellseq49362;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49358 Cellset49358;
typedef struct Pagedesc49354 Pagedesc49354;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Streamobj98227 Streamobj98227;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj99311 Stringstreamobj99311;
typedef struct Filestreamobj99467 Filestreamobj99467;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Ioerror4031  {
  Systemerror4029 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49346  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49362  {
NI len;
NI cap;
Cell49346** d;
};
struct  Cellset49358  {
NI counter;
NI max;
Pagedesc49354* head;
Pagedesc49354** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49362 zct;
Cellseq49362 decstack;
Cellset49358 cycleroots;
Cellseq49362 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
typedef N_NIMCALL_PTR(void, TY98228) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY98232) (Streamobj98227* s);
typedef N_NIMCALL_PTR(void, TY98236) (Streamobj98227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY98241) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NI, TY98245) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY98251) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98257) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98263) (Streamobj98227* s);
struct  Streamobj98227  {
  TNimObject Sup;
TY98228 closeimpl;
TY98232 atendimpl;
TY98236 setpositionimpl;
TY98241 getpositionimpl;
TY98245 readdataimpl;
TY98251 peekdataimpl;
TY98257 writedataimpl;
TY98263 flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
struct  Stringstreamobj99311  {
  Streamobj98227 Sup;
NimStringDesc* data;
NI pos;
};
struct  Filestreamobj99467  {
  Streamobj98227 Sup;
FILE* f;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49354  {
Pagedesc49354* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(Ioerror4031*, neweio_98205)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell49346*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49346* c);
N_NOINLINE(void, addzct_53017)(Cellseq49362* s, Cell49346* c);
N_NIMCALL(void, flush_98275)(Streamobj98227* s);
N_NIMCALL(void, close_98291)(Streamobj98227* s);
N_NIMCALL(void, close_98307)(Streamobj98227* s, Streamobj98227* unused);
N_NIMCALL(NIM_BOOL, atend_98317)(Streamobj98227* s);
N_NIMCALL(NIM_BOOL, atend_98327)(Streamobj98227* s, Streamobj98227* unused);
N_NIMCALL(void, setposition_98338)(Streamobj98227* s, NI pos);
N_NIMCALL(void, setposition_98348)(Streamobj98227* s, Streamobj98227* unused, NI pos);
N_NIMCALL(NI, getposition_98359)(Streamobj98227* s);
N_NIMCALL(NI, getposition_98369)(Streamobj98227* s, Streamobj98227* unused);
N_NIMCALL(NI, readdata_98380)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(NimStringDesc*, readall_98392)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NI, readdata_98423)(Streamobj98227* s, Streamobj98227* unused, void* buffer, NI buflen);
N_NIMCALL(NI, peekdata_98436)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_98448)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_98459)(Streamobj98227* s, Streamobj98227* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_98483)(Streamobj98227* s, NimStringDesc* x);
N_NIMCALL(void, writeln_98493)(Streamobj98227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, writeline_98526)(Streamobj98227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NIM_CHAR, readchar_98584)(Streamobj98227* s);
N_NIMCALL(NIM_CHAR, peekchar_98595)(Streamobj98227* s);
N_NIMCALL(void, read_98611)(Streamobj98227* s, NIM_BOOL* result);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_98606)(Streamobj98227* s);
N_NIMCALL(void, peek_98656)(Streamobj98227* s, NIM_BOOL* result);
N_NIMCALL(NIM_BOOL, peekbool_98651)(Streamobj98227* s);
N_NIMCALL(void, read_98698)(Streamobj98227* s, NI8* result);
N_NIMCALL(NI8, readint8_98693)(Streamobj98227* s);
N_NIMCALL(void, peek_98743)(Streamobj98227* s, NI8* result);
N_NIMCALL(NI8, peekint8_98738)(Streamobj98227* s);
N_NIMCALL(void, read_98785)(Streamobj98227* s, NI16* result);
N_NIMCALL(NI16, readint16_98780)(Streamobj98227* s);
N_NIMCALL(void, peek_98830)(Streamobj98227* s, NI16* result);
N_NIMCALL(NI16, peekint16_98825)(Streamobj98227* s);
N_NIMCALL(void, read_98872)(Streamobj98227* s, NI32* result);
N_NIMCALL(NI32, readint32_98867)(Streamobj98227* s);
N_NIMCALL(void, peek_98917)(Streamobj98227* s, NI32* result);
N_NIMCALL(NI32, peekint32_98912)(Streamobj98227* s);
N_NIMCALL(void, read_98959)(Streamobj98227* s, NI64* result);
N_NIMCALL(NI64, readint64_98954)(Streamobj98227* s);
N_NIMCALL(void, peek_99004)(Streamobj98227* s, NI64* result);
N_NIMCALL(NI64, peekint64_98999)(Streamobj98227* s);
N_NIMCALL(void, read_99046)(Streamobj98227* s, NF32* result);
N_NIMCALL(NF32, readfloat32_99041)(Streamobj98227* s);
N_NIMCALL(void, peek_99091)(Streamobj98227* s, NF32* result);
N_NIMCALL(NF32, peekfloat32_99086)(Streamobj98227* s);
N_NIMCALL(void, read_99133)(Streamobj98227* s, NF* result);
N_NIMCALL(NF, readfloat64_99128)(Streamobj98227* s);
N_NIMCALL(void, peek_99175)(Streamobj98227* s, NF* result);
N_NIMCALL(NF, peekfloat64_99170)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, readstr_99212)(Streamobj98227* s, NI length);
N_NIMCALL(NimStringDesc*, peekstr_99227)(Streamobj98227* s, NI length);
N_NIMCALL(NIM_BOOL, readline_99242)(Streamobj98227* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NIM_BOOL, peekline_99264)(Streamobj98227* s, NimStringDesc** line);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, readline_99277)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, peekline_99297)(Streamobj98227* s);
N_NIMCALL(NIM_BOOL, ssatend_99322)(Streamobj98227* s_99324);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_99339)(NI x, NI a, NI b);
N_NIMCALL(void, sssetposition_99333)(Streamobj98227* s_99335, NI pos);
N_NIMCALL(NI, ssgetposition_99358)(Streamobj98227* s_99360);
N_NIMCALL(NI, ssreaddata_99369)(Streamobj98227* s_99371, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, sspeekdata_99396)(Streamobj98227* s_99398, void* buffer, NI buflen);
N_NIMCALL(void, sswritedata_99414)(Streamobj98227* s_99416, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_99436)(Streamobj98227* s_99438);
N_NIMCALL(Stringstreamobj99311*, newstringstream_99446)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP160)(void* p, NI op);
N_NIMCALL(void, fsclose_99471)(Streamobj98227* s);
N_NIMCALL(void, fsflush_99489)(Streamobj98227* s);
N_NIMCALL(NIM_BOOL, fsatend_99495)(Streamobj98227* s);
N_NIMCALL(NIM_BOOL, endoffile_16860)(FILE* f);
N_NIMCALL(void, fssetposition_99502)(Streamobj98227* s, NI pos);
N_NIMCALL(void, setfilepos_16987)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_99509)(Streamobj98227* s);
N_NIMCALL(NI64, getfilepos_16991)(FILE* f);
N_NIMCALL(NI, fsreaddata_99517)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_16960)(FILE* f, void* buffer, NI len);
N_NIMCALL(NI, fspeekdata_99526)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(void, fswritedata_99536)(Streamobj98227* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_16982)(FILE* f, void* buffer, NI len);
N_NIMCALL(Filestreamobj99467*, newfilestream_99544)(FILE* f);
N_NIMCALL(void, TMP163)(void* p, NI op);
N_NIMCALL(Filestreamobj99467*, newfilestream_99559)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_16803)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
STRING_LITERAL(TMP146, "\015\012", 2);
STRING_LITERAL(TMP148, "cannot read from stream", 23);
STRING_LITERAL(TMP150, "", 0);
STRING_LITERAL(TMP162, "cannot write to stream", 22);
extern TNimType NTI16835; /* ref IOError */
extern TNimType NTI4031; /* IOError */
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
extern TSafePoint* exchandler_20843;
extern TNimType NTI4011; /* RootObj */
TNimType NTI98227; /* StreamObj */
TNimType NTI98228; /* proc (s: Stream){.gcsafe.} */
TNimType NTI98232; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI98236; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI98241; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI98245; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI98251; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI98257; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI98263; /* proc (s: Stream){.gcsafe.} */
TNimType NTI99311; /* StringStreamObj */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI99309; /* StringStream */
TNimType NTI99467; /* FileStreamObj */
extern TNimType NTI16404; /* File */
TNimType NTI99465; /* FileStream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49346*, usrtocell_53046)(void* usr) {
	Cell49346* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49346*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49346))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49346* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49346* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Ioerror4031*, neweio_98205)(NimStringDesc* msg) {
	Ioerror4031* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(38, "streams.nim");
	result = (Ioerror4031*) newObj((&NTI16835), sizeof(Ioerror4031));
	(*result).Sup.Sup.Sup.m_type = (&NTI4031);
	nimln(39, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_98275)(Streamobj98227* s) {
	nimfr("flush", "streams.nim")
	nimln(64, "streams.nim");
	{
		if (!!((*s).flushimpl == 0)) goto LA3;
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_98291)(Streamobj98227* s) {
	nimfr("close", "streams.nim")
	nimln(68, "streams.nim");
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_98307)(Streamobj98227* s, Streamobj98227* unused) {
	nimfr("close", "streams.nim")
	nimln(72, "streams.nim");
	(*s).closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_98317)(Streamobj98227* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(77, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_98327)(Streamobj98227* s, Streamobj98227* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(82, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_98338)(Streamobj98227* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(86, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_98348)(Streamobj98227* s, Streamobj98227* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(90, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_98359)(Streamobj98227* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(94, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_98369)(Streamobj98227* s, Streamobj98227* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(98, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_98380)(Streamobj98227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(102, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readall_98392)(Streamobj98227* s) {
	NimStringDesc* result;
	NI r;
	nimfr("readAll", "streams.nim")
	result = 0;
	nimln(107, "streams.nim");
	result = mnewString(((NI) 1000));
	nimln(108, "streams.nim");
	r = ((NI) 0);
	{
		nimln(109, "streams.nim");
		while (1) {
			NI readbytes;
			NI TMP143;
			NI TMP144;
			nimln(110, "streams.nim");
			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
			readbytes = readdata_98380(s, ((void*) ((&result->data[r]))), ((NI) 1000));
			nimln(111, "streams.nim");
			{
				NI TMP142;
				if (!(readbytes < ((NI) 1000))) goto LA5;
				nimln(112, "streams.nim");
				TMP142 = addInt(r, readbytes);
				result = setLengthStr(result, ((NI)chckRange((NI)(TMP142), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln(113, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(114, "streams.nim");
			TMP143 = addInt(r, ((NI) 1000));
			r = (NI)(TMP143);
			nimln(115, "streams.nim");
			TMP144 = addInt(r, ((NI) 1000));
			result = setLengthStr(result, ((NI)chckRange((NI)(TMP144), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_98423)(Streamobj98227* s, Streamobj98227* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(120, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, peekdata_98436)(Streamobj98227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("peekData", "streams.nim")
	result = 0;
	nimln(125, "streams.nim");
	result = (*s).peekdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_98448)(Streamobj98227* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(130, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_98459)(Streamobj98227* s, Streamobj98227* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(136, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_98483)(Streamobj98227* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(151, "streams.nim");
	writedata_98448(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
	popFrame();
}

N_NIMCALL(void, writeln_98493)(Streamobj98227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLn", "streams.nim")
	{
		NimStringDesc* str_98506;
		NI i_98510;
		str_98506 = 0;
		nimln(1965, "system.nim");
		i_98510 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP145;
				if (!(i_98510 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_98510) >= (NU)(argsLen0)) raiseIndexError();
				str_98506 = args[i_98510];
				nimln(155, "streams.nim");
				write_98483(s, str_98506);
				nimln(1968, "system.nim");
				TMP145 = addInt(i_98510, ((NI) 1));
				i_98510 = (NI)(TMP145);
			} LA3: ;
		}
	}
	nimln(156, "streams.nim");
	write_98483(s, ((NimStringDesc*) &TMP146));
	popFrame();
}

N_NIMCALL(void, writeline_98526)(Streamobj98227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLine", "streams.nim")
	{
		NimStringDesc* str_98539;
		NI i_98543;
		str_98539 = 0;
		nimln(1965, "system.nim");
		i_98543 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP147;
				if (!(i_98543 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_98543) >= (NU)(argsLen0)) raiseIndexError();
				str_98539 = args[i_98543];
				nimln(161, "streams.nim");
				write_98483(s, str_98539);
				nimln(1968, "system.nim");
				TMP147 = addInt(i_98543, ((NI) 1));
				i_98543 = (NI)(TMP147);
			} LA3: ;
		}
	}
	nimln(162, "streams.nim");
	write_98483(s, ((NimStringDesc*) &TMP146));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_98584)(Streamobj98227* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(177, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(177, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, peekchar_98595)(Streamobj98227* s) {
	NIM_CHAR result;
	nimfr("peekChar", "streams.nim")
	result = 0;
	nimln(182, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(182, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_98611)(Streamobj98227* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_98606)(Streamobj98227* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(186, "streams.nim");
	read_98611(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_98656)(Streamobj98227* s, NIM_BOOL* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, peekbool_98651)(Streamobj98227* s) {
	NIM_BOOL result;
	nimfr("peekBool", "streams.nim")
	result = 0;
	nimln(190, "streams.nim");
	peek_98656(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_98698)(Streamobj98227* s, NI8* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_98693)(Streamobj98227* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(194, "streams.nim");
	read_98698(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_98743)(Streamobj98227* s, NI8* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, peekint8_98738)(Streamobj98227* s) {
	NI8 result;
	nimfr("peekInt8", "streams.nim")
	result = 0;
	nimln(198, "streams.nim");
	peek_98743(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_98785)(Streamobj98227* s, NI16* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_98780)(Streamobj98227* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(202, "streams.nim");
	read_98785(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_98830)(Streamobj98227* s, NI16* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, peekint16_98825)(Streamobj98227* s) {
	NI16 result;
	nimfr("peekInt16", "streams.nim")
	result = 0;
	nimln(206, "streams.nim");
	peek_98830(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_98872)(Streamobj98227* s, NI32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_98867)(Streamobj98227* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(210, "streams.nim");
	read_98872(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_98917)(Streamobj98227* s, NI32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, peekint32_98912)(Streamobj98227* s) {
	NI32 result;
	nimfr("peekInt32", "streams.nim")
	result = 0;
	nimln(214, "streams.nim");
	peek_98917(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_98959)(Streamobj98227* s, NI64* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_98954)(Streamobj98227* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(218, "streams.nim");
	read_98959(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_99004)(Streamobj98227* s, NI64* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, peekint64_98999)(Streamobj98227* s) {
	NI64 result;
	nimfr("peekInt64", "streams.nim")
	result = 0;
	nimln(222, "streams.nim");
	peek_99004(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_99046)(Streamobj98227* s, NF32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_99041)(Streamobj98227* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(226, "streams.nim");
	read_99046(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_99091)(Streamobj98227* s, NF32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, peekfloat32_99086)(Streamobj98227* s) {
	NF32 result;
	nimfr("peekFloat32", "streams.nim")
	result = 0;
	nimln(230, "streams.nim");
	peek_99091(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_99133)(Streamobj98227* s, NF* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_98380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_99128)(Streamobj98227* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(234, "streams.nim");
	read_99133(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_99175)(Streamobj98227* s, NF* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_98436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP148));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, peekfloat64_99170)(Streamobj98227* s) {
	NF result;
	nimfr("peekFloat64", "streams.nim")
	result = 0;
	nimln(238, "streams.nim");
	peek_99175(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_99212)(Streamobj98227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(243, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(244, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = readdata_98380(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(245, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(245, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekstr_99227)(Streamobj98227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("peekStr", "streams.nim")
	result = 0;
	nimln(250, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(251, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = peekdata_98436(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(252, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(252, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_99242)(Streamobj98227* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
	nimln(261, "streams.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln(262, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(263, "streams.nim");
			c = readchar_98584(s);
			nimln(264, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(265, "streams.nim");
				c = readchar_98584(s);
				nimln(266, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(267, "streams.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8;
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(268, "streams.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11;
				nimln(269, "streams.nim");
				{
					nimln(357, "system.nim");
					nimln(269, "streams.nim");
					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(270, "streams.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(271, "streams.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln(272, "streams.nim");
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_20842 = s;
}

N_NIMCALL(NIM_BOOL, peekline_99264)(Streamobj98227* s, NimStringDesc** line) {
	NIM_BOOL volatile result;
	NI pos;
	TSafePoint TMP149;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(281, "streams.nim");
	pos = getposition_98359(s);
	nimln(282, "streams.nim");
	pushSafePoint(&TMP149);
	TMP149.status = setjmp(TMP149.context);
	if (TMP149.status == 0) {
		nimln(283, "streams.nim");
		result = readline_99242(s, line);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(282, "streams.nim");
		setposition_98338(s, pos);
	}
	if (TMP149.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_99277)(Streamobj98227* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(288, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP150));
	{
		nimln(289, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(290, "streams.nim");
			c = readchar_98584(s);
			nimln(291, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(292, "streams.nim");
				c = readchar_98584(s);
				nimln(293, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(294, "streams.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = ((NU8)(c) == (NU8)(10));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(c) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(295, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(297, "streams.nim");
				result = addChar(result, c);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekline_99297)(Streamobj98227* s) {
	NimStringDesc* volatile result;
	NI pos;
	TSafePoint TMP151;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(302, "streams.nim");
	pos = getposition_98359(s);
	nimln(303, "streams.nim");
	pushSafePoint(&TMP151);
	TMP151.status = setjmp(TMP151.context);
	if (TMP151.status == 0) {
		nimln(304, "streams.nim");
		result = readline_99277(s);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(303, "streams.nim");
		setposition_98338(s, pos);
	}
	if (TMP151.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_99322)(Streamobj98227* s_99324) {
	NIM_BOOL result;
	Stringstreamobj99311* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
	nimln(315, "streams.nim");
	if (s_99324) chckObj((*s_99324).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99324));
	nimln(316, "streams.nim");
	nimln(353, "system.nim");
	nimln(316, "streams.nim");
	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_99333)(Streamobj98227* s_99335, NI pos) {
	Stringstreamobj99311* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(319, "streams.nim");
	if (s_99335) chckObj((*s_99335).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99335));
	nimln(320, "streams.nim");
	(*s).pos = clamp_99339(pos, ((NI) 0), ((*s).data ? (*s).data->Sup.len : 0));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_99358)(Streamobj98227* s_99360) {
	NI result;
	Stringstreamobj99311* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
	nimln(323, "streams.nim");
	if (s_99360) chckObj((*s_99360).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99360));
	nimln(324, "streams.nim");
	result = (*s).pos;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_99369)(Streamobj98227* s_99371, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj99311* s;
	NI TMP154;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(327, "streams.nim");
	if (s_99371) chckObj((*s_99371).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99371));
	nimln(328, "streams.nim");
	TMP154 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP154)) ? buflen : (NI)(TMP154));
	nimln(329, "streams.nim");
	{
		NI TMP155;
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(330, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(331, "streams.nim");
		TMP155 = addInt((*s).pos, result);
		(*s).pos = (NI)(TMP155);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, sspeekdata_99396)(Streamobj98227* s_99398, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj99311* s;
	NI TMP156;
	nimfr("ssPeekData", "streams.nim")
	result = 0;
	nimln(334, "streams.nim");
	if (s_99398) chckObj((*s_99398).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99398));
	nimln(335, "streams.nim");
	TMP156 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP156)) ? buflen : (NI)(TMP156));
	nimln(336, "streams.nim");
	{
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(337, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_99414)(Streamobj98227* s_99416, void* buffer, NI buflen) {
	Stringstreamobj99311* s;
	NI TMP159;
	nimfr("ssWriteData", "streams.nim")
{	nimln(340, "streams.nim");
	if (s_99416) chckObj((*s_99416).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99416));
	nimln(341, "streams.nim");
	{
		if (!(buflen <= ((NI) 0))) goto LA3;
		nimln(342, "streams.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(343, "streams.nim");
	{
		NI TMP157;
		NI TMP158;
		nimln(357, "system.nim");
		nimln(343, "streams.nim");
		TMP157 = addInt((*s).pos, buflen);
		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP157))) goto LA7;
		nimln(344, "streams.nim");
		TMP158 = addInt((*s).pos, buflen);
		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP158), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA7: ;
	nimln(345, "streams.nim");
	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(346, "streams.nim");
	TMP159 = addInt((*s).pos, buflen);
	(*s).pos = (NI)(TMP159);
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, ssclose_99436)(Streamobj98227* s_99438) {
	Stringstreamobj99311* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(349, "streams.nim");
	if (s_99438) chckObj((*s_99438).Sup.m_type, (&NTI99311));
	s = ((Stringstreamobj99311*) (s_99438));
	nimln(350, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP160)(void* p, NI op) {
	Stringstreamobj99311* a;
	a = (Stringstreamobj99311*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringstreamobj99311*, newstringstream_99446)(NimStringDesc* s) {
	Stringstreamobj99311* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(354, "streams.nim");
	result = (Stringstreamobj99311*) newObj((&NTI99309), sizeof(Stringstreamobj99311));
	(*result).Sup.Sup.m_type = (&NTI99311);
	nimln(355, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).data; (*result).data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(356, "streams.nim");
	(*result).pos = ((NI) 0);
	nimln(357, "streams.nim");
	(*result).Sup.closeimpl = ssclose_99436;
	nimln(358, "streams.nim");
	(*result).Sup.atendimpl = ssatend_99322;
	nimln(359, "streams.nim");
	(*result).Sup.setpositionimpl = sssetposition_99333;
	nimln(360, "streams.nim");
	(*result).Sup.getpositionimpl = ssgetposition_99358;
	nimln(361, "streams.nim");
	(*result).Sup.readdataimpl = ssreaddata_99369;
	nimln(362, "streams.nim");
	(*result).Sup.peekdataimpl = sspeekdata_99396;
	nimln(363, "streams.nim");
	(*result).Sup.writedataimpl = sswritedata_99414;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_99471)(Streamobj98227* s) {
	nimfr("fsClose", "streams.nim")
	nimln(374, "streams.nim");
	{
		nimln(349, "system.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI99467));
		if (!!(((*((Filestreamobj99467*) (s))).f == NIM_NIL))) goto LA3;
		nimln(375, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI99467));
		fclose((*((Filestreamobj99467*) (s))).f);
		nimln(376, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI99467));
		(*((Filestreamobj99467*) (s))).f = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_99489)(Streamobj98227* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(377, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI99467));
	fflush((*((Filestreamobj99467*) (s))).f);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_99495)(Streamobj98227* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
	nimln(378, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI99467));
	result = endoffile_16860((*((Filestreamobj99467*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_99502)(Streamobj98227* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(379, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI99467));
	setfilepos_16987((*((Filestreamobj99467*) (s))).f, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_99509)(Streamobj98227* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
	nimln(380, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI99467));
	LOC1 = 0;
	LOC1 = getfilepos_16991((*((Filestreamobj99467*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_99517)(Streamobj98227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(383, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI99467));
	result = readbuffer_16960((*((Filestreamobj99467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(NI, fspeekdata_99526)(Streamobj98227* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP161;
	nimfr("fsPeekData", "streams.nim")
	result = 0;
	nimln(386, "streams.nim");
	pos = fsgetposition_99509(s);
	nimln(387, "streams.nim");
	pushSafePoint(&TMP161);
	TMP161.status = setjmp(TMP161.context);
	if (TMP161.status == 0) {
		nimln(388, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI99467));
		result = readbuffer_16960((*((Filestreamobj99467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(387, "streams.nim");
		fssetposition_99502(s, pos);
	}
	if (TMP161.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_99536)(Streamobj98227* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(391, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(391, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI99467));
		LOC3 = 0;
		LOC3 = writebuffer_16982((*((Filestreamobj99467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(392, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_98205(((NimStringDesc*) &TMP162));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP163)(void* p, NI op) {
	Filestreamobj99467* a;
	a = (Filestreamobj99467*)p;
}

N_NIMCALL(Filestreamobj99467*, newfilestream_99544)(FILE* f) {
	Filestreamobj99467* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(396, "streams.nim");
	result = (Filestreamobj99467*) newObj((&NTI99465), sizeof(Filestreamobj99467));
	(*result).Sup.Sup.m_type = (&NTI99467);
	nimln(397, "streams.nim");
	(*result).f = f;
	nimln(398, "streams.nim");
	(*result).Sup.closeimpl = fsclose_99471;
	nimln(399, "streams.nim");
	(*result).Sup.atendimpl = fsatend_99495;
	nimln(400, "streams.nim");
	(*result).Sup.setpositionimpl = fssetposition_99502;
	nimln(401, "streams.nim");
	(*result).Sup.getpositionimpl = fsgetposition_99509;
	nimln(402, "streams.nim");
	(*result).Sup.readdataimpl = fsreaddata_99517;
	nimln(403, "streams.nim");
	(*result).Sup.peekdataimpl = fspeekdata_99526;
	nimln(404, "streams.nim");
	(*result).Sup.writedataimpl = fswritedata_99536;
	nimln(405, "streams.nim");
	(*result).Sup.flushimpl = fsflush_99489;
	popFrame();
	return result;
}

N_NIMCALL(Filestreamobj99467*, newfilestream_99559)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj99467* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(412, "streams.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_16803(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_99544(f);
	}
	LA4: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void) {
static TNimNode* TMP152[8];
static TNimNode* TMP153[2];
static TNimNode TMP140[13];
NTI98227.size = sizeof(Streamobj98227);
NTI98227.kind = 17;
NTI98227.base = (&NTI4011);
NTI98227.flags = 1;
TMP152[0] = &TMP140[1];
NTI98228.size = sizeof(TY98228);
NTI98228.kind = 25;
NTI98228.base = 0;
NTI98228.flags = 3;
TMP140[1].kind = 1;
TMP140[1].offset = offsetof(Streamobj98227, closeimpl);
TMP140[1].typ = (&NTI98228);
TMP140[1].name = "closeImpl";
TMP152[1] = &TMP140[2];
NTI98232.size = sizeof(TY98232);
NTI98232.kind = 25;
NTI98232.base = 0;
NTI98232.flags = 3;
TMP140[2].kind = 1;
TMP140[2].offset = offsetof(Streamobj98227, atendimpl);
TMP140[2].typ = (&NTI98232);
TMP140[2].name = "atEndImpl";
TMP152[2] = &TMP140[3];
NTI98236.size = sizeof(TY98236);
NTI98236.kind = 25;
NTI98236.base = 0;
NTI98236.flags = 3;
TMP140[3].kind = 1;
TMP140[3].offset = offsetof(Streamobj98227, setpositionimpl);
TMP140[3].typ = (&NTI98236);
TMP140[3].name = "setPositionImpl";
TMP152[3] = &TMP140[4];
NTI98241.size = sizeof(TY98241);
NTI98241.kind = 25;
NTI98241.base = 0;
NTI98241.flags = 3;
TMP140[4].kind = 1;
TMP140[4].offset = offsetof(Streamobj98227, getpositionimpl);
TMP140[4].typ = (&NTI98241);
TMP140[4].name = "getPositionImpl";
TMP152[4] = &TMP140[5];
NTI98245.size = sizeof(TY98245);
NTI98245.kind = 25;
NTI98245.base = 0;
NTI98245.flags = 3;
TMP140[5].kind = 1;
TMP140[5].offset = offsetof(Streamobj98227, readdataimpl);
TMP140[5].typ = (&NTI98245);
TMP140[5].name = "readDataImpl";
TMP152[5] = &TMP140[6];
NTI98251.size = sizeof(TY98251);
NTI98251.kind = 25;
NTI98251.base = 0;
NTI98251.flags = 3;
TMP140[6].kind = 1;
TMP140[6].offset = offsetof(Streamobj98227, peekdataimpl);
TMP140[6].typ = (&NTI98251);
TMP140[6].name = "peekDataImpl";
TMP152[6] = &TMP140[7];
NTI98257.size = sizeof(TY98257);
NTI98257.kind = 25;
NTI98257.base = 0;
NTI98257.flags = 3;
TMP140[7].kind = 1;
TMP140[7].offset = offsetof(Streamobj98227, writedataimpl);
TMP140[7].typ = (&NTI98257);
TMP140[7].name = "writeDataImpl";
TMP152[7] = &TMP140[8];
NTI98263.size = sizeof(TY98263);
NTI98263.kind = 25;
NTI98263.base = 0;
NTI98263.flags = 3;
TMP140[8].kind = 1;
TMP140[8].offset = offsetof(Streamobj98227, flushimpl);
TMP140[8].typ = (&NTI98263);
TMP140[8].name = "flushImpl";
TMP140[0].len = 8; TMP140[0].kind = 2; TMP140[0].sons = &TMP152[0];
NTI98227.node = &TMP140[0];
NTI99311.size = sizeof(Stringstreamobj99311);
NTI99311.kind = 17;
NTI99311.base = (&NTI98227);
TMP153[0] = &TMP140[10];
TMP140[10].kind = 1;
TMP140[10].offset = offsetof(Stringstreamobj99311, data);
TMP140[10].typ = (&NTI149);
TMP140[10].name = "data";
TMP153[1] = &TMP140[11];
TMP140[11].kind = 1;
TMP140[11].offset = offsetof(Stringstreamobj99311, pos);
TMP140[11].typ = (&NTI108);
TMP140[11].name = "pos";
TMP140[9].len = 2; TMP140[9].kind = 2; TMP140[9].sons = &TMP153[0];
NTI99311.node = &TMP140[9];
NTI99309.size = sizeof(Stringstreamobj99311*);
NTI99309.kind = 22;
NTI99309.base = (&NTI99311);
NTI99309.marker = TMP160;
NTI99467.size = sizeof(Filestreamobj99467);
NTI99467.kind = 17;
NTI99467.base = (&NTI98227);
NTI99467.flags = 1;
TMP140[12].kind = 1;
TMP140[12].offset = offsetof(Filestreamobj99467, f);
TMP140[12].typ = (&NTI16404);
TMP140[12].name = "f";
NTI99467.node = &TMP140[12];
NTI99465.size = sizeof(Filestreamobj99467*);
NTI99465.kind = 22;
NTI99465.base = (&NTI99467);
NTI99465.marker = TMP163;
}

