/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o e:\nim\stream\2015_11_29\nimcache\tinttoas.o e:\nim\stream\2015_11_29\nimcache\tinttoas.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct Filestreamobj99467 Filestreamobj99467;
typedef struct Cell49346 Cell49346;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cellset49358 Cellset49358;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49362 Cellseq49362;
typedef struct Pagedesc49354 Pagedesc49354;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Stringstreamobj99311 Stringstreamobj99311;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Streamobj98227 Streamobj98227;
typedef struct TNimObject TNimObject;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  Cell49346  {
NI refcount;
TNimType* typ;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  Cellseq49362  {
NI len;
NI cap;
Cell49346** d;
};
struct  Cellset49358  {
NI counter;
NI max;
Pagedesc49354* head;
Pagedesc49354** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49362 zct;
Cellseq49362 decstack;
Cellset49358 cycleroots;
Cellseq49362 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimObject  {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY98228) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY98232) (Streamobj98227* s);
typedef N_NIMCALL_PTR(void, TY98236) (Streamobj98227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY98241) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NI, TY98245) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY98251) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98257) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98263) (Streamobj98227* s);
struct  Streamobj98227  {
  TNimObject Sup;
TY98228 closeimpl;
TY98232 atendimpl;
TY98236 setpositionimpl;
TY98241 getpositionimpl;
TY98245 readdataimpl;
TY98251 peekdataimpl;
TY98257 writedataimpl;
TY98263 flushimpl;
};
struct  Filestreamobj99467  {
  Streamobj98227 Sup;
FILE* f;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49354  {
Pagedesc49354* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Stringstreamobj99311  {
  Streamobj98227 Sup;
NimStringDesc* data;
NI pos;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(Filestreamobj99467*, newfilestream_99544)(FILE* f);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49346* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49346* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49346* c);
N_NOINLINE(void, incl_50065)(Cellset49358* s, Cell49346* cell);
static N_INLINE(Cell49346*, usrtocell_53046)(void* usr);
static N_INLINE(void, decref_55004)(Cell49346* c);
static N_INLINE(void, rtladdzct_54604)(Cell49346* c);
N_NOINLINE(void, addzct_53017)(Cellseq49362* s, Cell49346* c);
N_NIMCALL(Stringstreamobj99311*, newstringstream_99446)(NimStringDesc* s);
N_NIMCALL(NI32, readint32_98867)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, Streamreadinttostring_101059)(NI32 strint, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, tinttoasInit000)(void);
NIM_EXTERNC N_NOINLINE(void, tinttoasDatInit000)(void);
STRING_LITERAL(TMP164, "0123456789", 10);
STRING_LITERAL(TMP165, "2", 1);
STRING_LITERAL(TMP166, "", 0);
STRING_LITERAL(TMP170, "strInt1 =  ", 11);
STRING_LITERAL(TMP171, "strInt2 =  ", 11);
Filestreamobj99467* fs_101028;
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
Stringstreamobj99311* ss_101029;
NI32 strint1_101030;
NI32 strint2_101031;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49346* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49346* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49346* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell49346*, usrtocell_53046)(void* usr) {
	Cell49346* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49346*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49346))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49346* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49346* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49346* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49346* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, Streamreadinttostring_101059)(NI32 strint, NI size) {
	NimStringDesc* result_101066;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NI32 temp;
	NI judge;
	NIM_CHAR singlechar;
	NI singleint;
	NimStringDesc* result;
	nimfr("StreamReadIntToString", "tinttoas.nim")
{	result_101066 = 0;
	nimln(6, "tinttoas.nim");
	LOC1 = 0;
	LOC1 = nimIntToStr(((NI) (strint)));
	LOC2 = 0;
	LOC2 = nimIntToStr(size);
	printf("%s%s\015\012", LOC1? (LOC1)->data:"nil", LOC2? (LOC2)->data:"nil");
	nimln(8, "tinttoas.nim");
	temp = strint;
	nimln(9, "tinttoas.nim");
	judge = size;
	singlechar = 0;
	singleint = 0;
	nimln(12, "tinttoas.nim");
	result = copyString(((NimStringDesc*) &TMP166));
	{
		nimln(14, "tinttoas.nim");
		while (1) {
			NI TMP167;
			NI TMP168;
			NI TMP169;
			NimStringDesc* LOC5;
			NimStringDesc* LOC6;
			nimln(357, "system.nim");
			if (!(((NI) 0) < judge)) goto LA4;
			nimln(15, "tinttoas.nim");
			TMP167 = subInt(judge, ((NI) 1));
			judge = (NI)(TMP167);
			nimln(16, "tinttoas.nim");
			TMP168 = subInt(size, ((NI) 1));
			TMP169 = mulInt((NI)(TMP168), ((NI) 8));
			singleint = (NI)((NU64)(((NI) (temp))) >> (NU64)((NI)(TMP169)));
			nimln(17, "tinttoas.nim");
			LOC5 = 0;
			LOC5 = nimIntToStr(singleint);
			printf("%s\015\012", LOC5? (LOC5)->data:"nil");
			nimln(18, "tinttoas.nim");
			singlechar = ((NIM_CHAR)chckRange(singleint, 0, 255));
			nimln(19, "tinttoas.nim");
			LOC6 = 0;
			LOC6 = rawNewString(result->Sup.len + 1);
appendChar(LOC6, singlechar);
appendString(LOC6, result);
			result = LOC6;
			nimln(21, "tinttoas.nim");
			{
				NimStringDesc* LOC11;
				nimln(357, "system.nim");
				if (!(((NI) 0) < judge)) goto LA9;
				nimln(22, "tinttoas.nim");
				temp = (NI32)((NU32)(temp) << (NU32)(((NI32) 8)));
				nimln(23, "tinttoas.nim");
				LOC11 = 0;
				LOC11 = nimIntToStr(((NI) (temp)));
				printf("%s\015\012", LOC11? (LOC11)->data:"nil");
			}
			goto LA7;
			LA9: ;
			{
				nimln(25, "tinttoas.nim");
				result_101066 = copyString(result);
				goto BeforeRet;
			}
			LA7: ;
		} LA4: ;
	}
	}BeforeRet: ;
	popFrame();
	return result_101066;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_streamsDatInit000();
	tinttoasDatInit000();
	HEX00_streamsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	tinttoasInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, tinttoasInit000)(void) {
	Streamobj98227* LOC1;
	Streamobj98227* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("tinttoas", "tinttoas.nim")
	nimln(28, "tinttoas.nim");
	asgnRef((void**) (&fs_101028), newfilestream_99544(stdin));
	nimln(29, "tinttoas.nim");
	asgnRef((void**) (&ss_101029), newstringstream_99446(((NimStringDesc*) &TMP164)));
	nimln(32, "tinttoas.nim");
	printf("%s\015\012", ((NimStringDesc*) &TMP165)? (((NimStringDesc*) &TMP165))->data:"nil");
	nimln(33, "tinttoas.nim");
	LOC1 = 0;
	LOC1 = &fs_101028->Sup;
	strint1_101030 = readint32_98867(LOC1);
	nimln(34, "tinttoas.nim");
	LOC2 = 0;
	LOC2 = &ss_101029->Sup;
	strint2_101031 = readint32_98867(LOC2);
	nimln(35, "tinttoas.nim");
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (strint2_101031)));
	printf("%s\015\012", LOC3? (LOC3)->data:"nil");
	nimln(38, "tinttoas.nim");
	LOC4 = 0;
	LOC4 = Streamreadinttostring_101059(strint1_101030, ((NI) 4));
	printf("%s%s\015\012", ((NimStringDesc*) &TMP170)? (((NimStringDesc*) &TMP170))->data:"nil", LOC4? (LOC4)->data:"nil");
	nimln(39, "tinttoas.nim");
	LOC5 = 0;
	LOC5 = Streamreadinttostring_101059(strint2_101031, ((NI) 4));
	printf("%s%s\015\012", ((NimStringDesc*) &TMP171)? (((NimStringDesc*) &TMP171))->data:"nil", LOC5? (LOC5)->data:"nil");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, tinttoasDatInit000)(void) {
}

