/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o e:\nim\stream\2015_11_29\nimcache\tstringreadint.o e:\nim\stream\2015_11_29\nimcache\tstringreadint.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct Stringstreamobj99311 Stringstreamobj99311;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell49346 Cell49346;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cellset49358 Cellset49358;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49362 Cellseq49362;
typedef struct Pagedesc49354 Pagedesc49354;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Streamobj98227 Streamobj98227;
typedef struct TNimObject TNimObject;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Cell49346  {
NI refcount;
TNimType* typ;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  Cellseq49362  {
NI len;
NI cap;
Cell49346** d;
};
struct  Cellset49358  {
NI counter;
NI max;
Pagedesc49354* head;
Pagedesc49354** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49362 zct;
Cellseq49362 decstack;
Cellset49358 cycleroots;
Cellseq49362 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY98228) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY98232) (Streamobj98227* s);
typedef N_NIMCALL_PTR(void, TY98236) (Streamobj98227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY98241) (Streamobj98227* s);
typedef N_NIMCALL_PTR(NI, TY98245) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY98251) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98257) (Streamobj98227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY98263) (Streamobj98227* s);
struct  Streamobj98227  {
  TNimObject Sup;
TY98228 closeimpl;
TY98232 atendimpl;
TY98236 setpositionimpl;
TY98241 getpositionimpl;
TY98245 readdataimpl;
TY98251 peekdataimpl;
TY98257 writedataimpl;
TY98263 flushimpl;
};
struct  Stringstreamobj99311  {
  Streamobj98227 Sup;
NimStringDesc* data;
NI pos;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49354  {
Pagedesc49354* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(Stringstreamobj99311*, newstringstream_99446)(NimStringDesc* s);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49346* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49346* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49346* c);
N_NOINLINE(void, incl_50065)(Cellset49358* s, Cell49346* cell);
static N_INLINE(Cell49346*, usrtocell_53046)(void* usr);
static N_INLINE(void, decref_55004)(Cell49346* c);
static N_INLINE(void, rtladdzct_54604)(Cell49346* c);
N_NOINLINE(void, addzct_53017)(Cellseq49362* s, Cell49346* c);
N_NIMCALL(NI8, readint8_98693)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NI, getposition_98359)(Streamobj98227* s);
N_NIMCALL(NI16, readint16_98780)(Streamobj98227* s);
N_NIMCALL(NI32, readint32_98867)(Streamobj98227* s);
N_NIMCALL(NI64, readint64_98954)(Streamobj98227* s);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, tstringreadintInit000)(void);
NIM_EXTERNC N_NOINLINE(void, tstringreadintDatInit000)(void);
STRING_LITERAL(TMP164, "00100023456789012345", 20);
STRING_LITERAL(TMP165, "==================================", 34);
STRING_LITERAL(TMP166, "01", 2);
Stringstreamobj99311* ss_101004;
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
Stringstreamobj99311* ss2_101053;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49346* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49346* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49346* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell49346*, usrtocell_53046)(void* usr) {
	Cell49346* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49346*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49346))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49346* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49346* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49346* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49346* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_streamsDatInit000();
	tstringreadintDatInit000();
	HEX00_streamsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	tstringreadintInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, tstringreadintInit000)(void) {
	Streamobj98227* LOC1;
	NI8 LOC2;
	NimStringDesc* LOC3;
	Streamobj98227* LOC4;
	NI LOC5;
	NimStringDesc* LOC6;
	Streamobj98227* LOC7;
	NI16 LOC8;
	NimStringDesc* LOC9;
	Streamobj98227* LOC10;
	NI LOC11;
	NimStringDesc* LOC12;
	Streamobj98227* LOC13;
	NI32 LOC14;
	NimStringDesc* LOC15;
	Streamobj98227* LOC16;
	NI LOC17;
	NimStringDesc* LOC18;
	Streamobj98227* LOC19;
	NI64 LOC20;
	NimStringDesc* LOC21;
	Streamobj98227* LOC22;
	NI LOC23;
	NimStringDesc* LOC24;
	Streamobj98227* LOC25;
	NI16 LOC26;
	NimStringDesc* LOC27;
	Streamobj98227* LOC28;
	NI LOC29;
	NimStringDesc* LOC30;
	nimfr("tstringreadint", "tstringreadint.nim")
	nimln(4, "tstringreadint.nim");
	asgnRef((void**) (&ss_101004), newstringstream_99446(((NimStringDesc*) &TMP164)));
	nimln(6, "tstringreadint.nim");
	LOC1 = 0;
	LOC1 = &ss_101004->Sup;
	LOC2 = 0;
	LOC2 = readint8_98693(LOC1);
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (LOC2)));
	printf("%s\015\012", LOC3? (LOC3)->data:"nil");
	nimln(7, "tstringreadint.nim");
	LOC4 = 0;
	LOC4 = &ss_101004->Sup;
	LOC5 = 0;
	LOC5 = getposition_98359(LOC4);
	LOC6 = 0;
	LOC6 = nimIntToStr(LOC5);
	printf("%s\015\012", LOC6? (LOC6)->data:"nil");
	nimln(9, "tstringreadint.nim");
	LOC7 = 0;
	LOC7 = &ss_101004->Sup;
	LOC8 = 0;
	LOC8 = readint16_98780(LOC7);
	LOC9 = 0;
	LOC9 = nimIntToStr(((NI) (LOC8)));
	printf("%s\015\012", LOC9? (LOC9)->data:"nil");
	nimln(10, "tstringreadint.nim");
	LOC10 = 0;
	LOC10 = &ss_101004->Sup;
	LOC11 = 0;
	LOC11 = getposition_98359(LOC10);
	LOC12 = 0;
	LOC12 = nimIntToStr(LOC11);
	printf("%s\015\012", LOC12? (LOC12)->data:"nil");
	nimln(12, "tstringreadint.nim");
	LOC13 = 0;
	LOC13 = &ss_101004->Sup;
	LOC14 = 0;
	LOC14 = readint32_98867(LOC13);
	LOC15 = 0;
	LOC15 = nimIntToStr(((NI) (LOC14)));
	printf("%s\015\012", LOC15? (LOC15)->data:"nil");
	nimln(13, "tstringreadint.nim");
	LOC16 = 0;
	LOC16 = &ss_101004->Sup;
	LOC17 = 0;
	LOC17 = getposition_98359(LOC16);
	LOC18 = 0;
	LOC18 = nimIntToStr(LOC17);
	printf("%s\015\012", LOC18? (LOC18)->data:"nil");
	nimln(15, "tstringreadint.nim");
	LOC19 = 0;
	LOC19 = &ss_101004->Sup;
	LOC20 = 0;
	LOC20 = readint64_98954(LOC19);
	LOC21 = 0;
	LOC21 = nimInt64ToStr(LOC20);
	printf("%s\015\012", LOC21? (LOC21)->data:"nil");
	nimln(16, "tstringreadint.nim");
	LOC22 = 0;
	LOC22 = &ss_101004->Sup;
	LOC23 = 0;
	LOC23 = getposition_98359(LOC22);
	LOC24 = 0;
	LOC24 = nimIntToStr(LOC23);
	printf("%s\015\012", LOC24? (LOC24)->data:"nil");
	nimln(18, "tstringreadint.nim");
	printf("%s\015\012", ((NimStringDesc*) &TMP165)? (((NimStringDesc*) &TMP165))->data:"nil");
	nimln(20, "tstringreadint.nim");
	asgnRef((void**) (&ss2_101053), newstringstream_99446(((NimStringDesc*) &TMP166)));
	nimln(22, "tstringreadint.nim");
	LOC25 = 0;
	LOC25 = &ss2_101053->Sup;
	LOC26 = 0;
	LOC26 = readint16_98780(LOC25);
	LOC27 = 0;
	LOC27 = nimIntToStr(((NI) (LOC26)));
	printf("%s\015\012", LOC27? (LOC27)->data:"nil");
	nimln(23, "tstringreadint.nim");
	LOC28 = 0;
	LOC28 = &ss2_101053->Sup;
	LOC29 = 0;
	LOC29 = getposition_98359(LOC28);
	LOC30 = 0;
	LOC30 = nimIntToStr(LOC29);
	printf("%s\015\012", LOC30? (LOC30)->data:"nil");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, tstringreadintDatInit000)(void) {
}

